//import { getToken } from '@/utils/authHelpers';
import { moduleRoute } from '../../routeControl/route';

//const token = getToken();
const isV2LoyaltyRoutesArr = [
  {
    id: 'loyalty-dashboard',
    label: 'Dashboard',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_dashboard',
    nav: 'loyaltyDashboard',
    href: moduleRoute?.loyalty_rewards?.dashboard,
    eventName: 'left_menu_loyalty_rewards_dashboard',
  },
  {
    id: 'loyalty-setup-program',
    label: 'Set up program',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_ev_rewards',
    nav: 'SetupProgram',
    subMenu: [
      {
        id: 'loyalty-earn-points',
        label: 'Earn points',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_activity',
        nav: 'earnPoints',
        href: moduleRoute?.loyalty_rewards?.earn_points,
        eventName: 'left_menu_loyalty_rewards_earn_points',
      },
      {
        id: 'loyalty-redeem-points',
        label: 'Redeem points',
        feature_id: 'loyalty_reward',
        nav: 'redeemPoints',
        href: moduleRoute?.loyalty_rewards?.redeem_points,
        eventName: 'left_menu_loyalty_rewards_redeem_points',
      },
      {
        id: 'loyalty-vip-program',
        label: 'VIP program',
        feature_id: 'loyalty_reward',
        ai_module_feture: 'loyalty_rewards_tier_system',
        plan_id: 'loyalty_tier_system',
        module_feature: 'loyalty_rewards_tier_system',
        nav: 'VIPProgram',
        href: moduleRoute?.loyalty_rewards?.vip_program,
        eventName: 'left_menu_loyalty_rewards_vip_program',

        // createButton: {
        //   href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/tier-createnewtier?ai_v2=${token}`,
        //   eventName: 'left_menu_loyalty_rewards_create_vip_program',
        // },
      },
      {
        id: 'loyalty-gift-code',
        label: 'Gift code',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_purchase_code',
        nav: 'giftCode',
        href: moduleRoute?.loyalty_rewards?.gift_code,
        eventName: 'left_menu_loyalty_rewards_gift_code',
      },
      {
        id: 'loyalty-reward-orders',
        label: 'Reward orders',
        feature_id: 'loyalty_reward',
        nav: 'rewardOrders',
        href: moduleRoute?.loyalty_rewards?.reward_order,
        eventName: 'left_menu_loyalty_rewards_reward_orders',
      },
      {
        id: 'loyalty-product-reward-gallery',
        label: 'Free product reward gallery',
        feature_id: 'loyalty_reward',
        nav: 'productRewardGallery',
        href: moduleRoute?.loyalty_rewards?.free_product_reward_gallary,
        eventName: 'left_menu_loyalty_rewards_reward_orders',
      },
      {
        id: 'loyalty-product-reward-settings',
        label: 'Free product reward settings',
        feature_id: 'loyalty_reward',
        nav: 'productRewardSettings',
        href: moduleRoute?.loyalty_rewards?.free_product_reward_setting,
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/reward-freeproductreward#/freerewardsetting?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_reward_orders',
      },
      {
        id: 'loyalty-point-expiry',
        label: 'Point expiry',
        feature_id: 'loyalty_reward',
        ai_module_feture: 'loyalty_rewards_point_expiry',
        module_feature: 'loyalty_rewards_point_expiry',
        nav: 'PointExpiry',
        href: moduleRoute?.loyalty_rewards?.point_expiry,
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/reward-pointexpire?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_reward_orders',
      },
    ],
  },
  {
    id: 'loyalty-display-on-store',
    label: 'Display on store',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_setting',
    nav: 'displayOnStore',
    href: moduleRoute?.loyalty_rewards?.display_on_store,
    eventName: 'left_menu_loyalty_rewards_display_on_store',
  },
  {
    id: 'loyalty-members',
    label: 'Members',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_ev_rewards',
    nav: 'Members',
    subMenu: [
      {
        id: 'loyalty-members-loyalty',
        label: 'Members list',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_engaged_member',
        nav: 'engagedMembers',
        href: moduleRoute?.loyalty_rewards?.loyalty_members,
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/members-list?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_engaged_members',
      },
      // {
      //   id: 'loyalty-members-all',
      //   label: 'All members',
      //   feature_id: 'loyalty_reward',
      //   plan_id: 'loyalty_all_member',
      //   nav: 'allMembers',
      //   href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/members-customerlist?ai_v2=${token}`,
      //   eventName: 'left_menu_loyalty_rewards_all_members',
      // },
      {
        id: 'loyalty-members-import',
        label: 'Import members',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_csv_import',
        nav: 'ImportMembers',
        href: moduleRoute?.loyalty_rewards?.import_members,
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/members-csvtracking?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_import_members',
      },
      {
        id: 'loyalty-vip-program',
        label: 'Import VIP Members',
        feature_id: 'loyalty_reward',
        ai_module_feture: 'loyalty_rewards_tier_system',
        plan_id: 'loyalty_tier_system',
        module_feature: 'loyalty_rewards_tier_system',
        nav: 'VIPProgram',
        href: moduleRoute?.loyalty_rewards?.import_members_into_vip_tiers,
        eventName: 'left_menu_loyalty_rewards_vip_program',
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/members-csvtracking?ai_v2=${token}`,
      },
    ],
  },
  {
    id: 'loyalty-settings',
    label: 'Settings',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_ev_rewards',
    nav: 'loyaltySettings',
    subMenu: [
      {
        id: 'loyalty-settings-general',
        label: 'General settings',
        ai_module_feature: 'loyalty_rewards_point_expiry',
        feature_id: 'loyalty_reward',
        module_feature: 'loyalty_rewards_point_expiry',
        nav: 'blocktag',
        href: moduleRoute?.loyalty_rewards?.general_settings,
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/reward-generalsettings?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_point_expiry',
      },
      {
        id: 'loyalty-settings-email',
        label: 'Email settings',
        nav: 'loyaltyEmailSettings',
        href: moduleRoute?.loyalty_rewards?.email_settings,
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/loyalty/emailsettings?ai_v2=${token}`,
        eventName: 'left_loyalty_email_settings',
      },
      {
        id: 'loyalty-settings-language',
        label: 'Language settings',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_language',
        nav: 'LanguageSettings',
        href: moduleRoute?.loyalty_rewards?.language_settings,
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/language-setup?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_language_settings',
      },
    ],
  },
  {
    id: 'loyalty-analytics',
    label: 'Analytics',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_ev_rewards',
    nav: 'loyaltyAnalytics',
    subMenu: [
      {
        id: 'loyalty-analytics-discount-codes',
        label: 'Discount codes',
        feature_id: 'loyalty_reward',
        nav: 'DiscountCodes',
        href: moduleRoute?.loyalty_rewards?.discount_report,
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/reward-coupanlist?coupan_type=1&ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_discount_codes',
      },
      {
        id: 'loyalty-analytics-activity-report',
        label: 'Activity report',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_activity_stream',
        nav: 'PointActivity',
        href: moduleRoute?.loyalty_rewards?.activity_report,
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/loyalty-activitystream?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_point_activity',
      },
    ],
  },
];

const isV1LoyaltyRoutesArr = (encodedShopId, token) => [
  {
    id: 'loyalty-dashboard',
    label: 'Dashboard',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_dashboard',
    nav: 'loyaltyDashboard',
    href: 'loyalty/loyalty/home',
    href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/loyalty-home?ai_v2=${token}`,
    eventName: 'left_menu_loyalty_rewards_dashboard',
  },
  {
    id: 'loyalty-setup-program',
    label: 'Set up program',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_ev_rewards',
    nav: 'SetupProgram',
    subMenu: [
      {
        id: 'loyalty-earn-points',
        label: 'Earn points',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_activity',
        nav: 'earnPoints',
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/rule-createnew?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_earn_points',
      },
      {
        id: 'loyalty-redeem-points',
        label: 'Redeem points',
        feature_id: 'loyalty_reward',
        nav: 'redeemPoints',
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/reward-createnewreward?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_redeem_points',
      },
      {
        id: 'loyalty-vip-program',
        label: 'VIP program',
        feature_id: 'loyalty_reward',
        ai_module_feture: 'loyalty_rewards_tier_system',
        plan_id: 'loyalty_tier_system',
        module_feature: 'loyalty_rewards_tier_system',
        nav: 'VIPProgram',
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/tierlist?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_vip_program',
        createButton: {
          href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/tier-createnewtier?ai_v2=${token}`,
          eventName: 'left_menu_loyalty_rewards_create_vip_program',
        },
      },
      {
        id: 'loyalty-gift-code',
        label: 'Gift code',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_purchase_code',
        nav: 'giftCode',
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/loyalty-shoprewards?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_gift_code',
      },
      {
        id: 'loyalty-reward-orders',
        label: 'Reward orders',
        feature_id: 'loyalty_reward',
        nav: 'rewardOrders',
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/loyalty-rewardshoporders#/rewardorders?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_reward_orders',
      },
      {
        id: 'loyalty-product-reward-gallery',
        label: 'Free product reward gallery',
        feature_id: 'loyalty_reward',
        nav: 'productRewardGallery',
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/reward/freeproductrewardmain#/gridreward?ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/reward-freeproductrewardmain#/gridreward?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_reward_orders',
      },
      {
        id: 'loyalty-product-reward-settings',
        label: 'Free product reward settings',
        feature_id: 'loyalty_reward',
        nav: 'productRewardSettings',
        //href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/reward/freeproductreward#/freerewardsetting?ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/reward-freeproductreward#/freerewardsetting?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_reward_orders',
      },
      {
        id: 'loyalty-point-expiry',
        label: 'Point expiry',
        feature_id: 'loyalty_reward',
        ai_module_feture: 'loyalty_rewards_point_expiry',
        module_feature: 'loyalty_rewards_point_expiry',
        nav: 'PointExpiry',
        //href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/reward/pointexpire?ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/reward-pointexpire?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_reward_orders',
      },
    ],
  },
  {
    id: 'loyalty-display-on-store',
    label: 'Display on store',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_setting',
    nav: 'displayOnStore',
    // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/loyalty/setting?ai_v2=${token}`,
    href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/loyalty-setting?ai_v2=${token}`,
    eventName: 'left_menu_loyalty_rewards_display_on_store',
  },
  {
    id: 'loyalty-members',
    label: 'Members',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_ev_rewards',
    nav: 'Members',
    subMenu: [
      {
        id: 'loyalty-members-loyalty',
        label: 'Loyalty members',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_engaged_member',
        nav: 'engagedMembers',
        //href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/members/list?ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/members-list?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_engaged_members',
      },
      {
        id: 'loyalty-members-all',
        label: 'All members',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_all_member',
        nav: 'allMembers',
        // href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/members/customerlist?ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/members-customerlist?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_all_members',
      },
      {
        id: 'loyalty-members-import',
        label: 'Import members',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_csv_import',
        nav: 'ImportMembers',
        //href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/members/csvtracking?ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/members-csvtracking?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_import_members',
      },
    ],
  },
  {
    id: 'loyalty-settings',
    label: 'Settings',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_ev_rewards',
    nav: 'loyaltySettings',
    subMenu: [
      {
        id: 'loyalty-settings-general',
        label: 'General settings',
        ai_module_feature: 'loyalty_rewards_point_expiry',
        feature_id: 'loyalty_reward',
        module_feature: 'loyalty_rewards_point_expiry',
        nav: 'blocktag',
        //href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/reward/generalsettings?ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/reward-generalsettings?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_point_expiry',
      },
      {
        id: 'loyalty-settings-email',
        label: 'Email settings',
        nav: 'loyaltyEmailSettings',
        //href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/loyalty/emailsettings?ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/loyalty/emailsettings?ai_v2=${token}`,
        eventName: 'left_loyalty_email_settings',
      },
      {
        id: 'loyalty-settings-language',
        label: 'Language settings',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_language',
        nav: 'LanguageSettings',
        //href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/language/setup?ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/language-setup?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_language_settings',
      },
    ],
  },
  {
    id: 'loyalty-analytics',
    label: 'Analytics',
    feature_id: 'loyalty_reward',
    plan_id: 'loyalty_ev_rewards',
    nav: 'loyaltyAnalytics',
    subMenu: [
      {
        id: 'loyalty-analytics-discount-codes',
        label: 'Discount codes',
        feature_id: 'loyalty_reward',
        nav: 'DiscountCodes',
        //href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/reward/coupanlist?coupan_type=1&ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/reward-coupanlist?coupan_type=1&ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_discount_codes',
      },
      {
        id: 'loyalty-analytics-activity-report',
        label: 'Activity report',
        feature_id: 'loyalty_reward',
        plan_id: 'loyalty_activity_stream',
        nav: 'PointActivity',
        //href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/loyalty/activitystream?ai_v2=${token}`,
        href: `${process.env.NEXT_PUBLIC_APP_URL}/loyalty/index/index/q/${encodedShopId}/url/loyalty-activitystream?ai_v2=${token}`,
        eventName: 'left_menu_loyalty_rewards_point_activity',
      },
    ],
  },
];

const removeVipProgramForWoo = (routes, shopType) => {
  if (shopType !== 'woocommerce') return routes;

  return routes.map((route) =>
    route.subMenu
      ? {
          ...route,
          subMenu: route.subMenu.filter(
            (sub) =>
              sub?.label !== 'VIP program' &&
              sub?.label !== 'Import VIP Members'
          ),
        }
      : route
  );
};

export const getLoyaltyRewardsRoute = (
  is_enable_loyalty_v2,
  encodedShopId = null,
  token,
  userDetails
) => {
  return is_enable_loyalty_v2
    ? removeVipProgramForWoo(
        isV2LoyaltyRoutesArr,
        userDetails?.login_auth?.shop_type
      )
    : removeVipProgramForWoo(
        isV1LoyaltyRoutesArr(encodedShopId, token),
        userDetails?.login_auth?.shop_type
      );
};
