version: 0.0
os: linux

# ──────────────────────────────────────────────────────────────
# AWS CodeDeploy AppSpec — Parameterized for All Environments
# ──────────────────────────────────────────────────────────────
# Deployment flow (optimized for minimal downtime):
#
#   1. ApplicationStop   → No-op (app keeps running)
#   2. BeforeInstall     → Prepares directories, cleans temp files
#   3. (CodeDeploy copies artifact to /tmp/codedeploy_artifact)
#   4. AfterInstall      → Stops PM2, backs up httpdocs, swaps new build
#   5. ApplicationStart  → npm rebuild, starts PM2, cleans old backups
#
# PM2 stops only at step 4 right before the swap — app stays
# running during steps 1-3 while files are being prepared and copied.
# ──────────────────────────────────────────────────────────────

files:
  - source: /
    destination: /tmp/codedeploy_artifact

hooks:
  ApplicationStop:
    - location: appspec-script/application_stop.sh
      timeout: 30
      runas: root

  BeforeInstall:
    - location: appspec-script/before_install.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: appspec-script/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: appspec-script/application_start.sh
      timeout: 120
      runas: root