version: 0.2

env:
  variables:
    ENV_NAME: "ai-dev-front2"
    APP_PORT: "3005"
    BASE_DIR: "/srv/aitrillion.com/subdomains/ai-dev-front2"
  exported-variables:
    - ENV_NAME
    - APP_PORT
    - BASE_DIR

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "=== Install Phase ==="
      - echo "Environment - $ENV_NAME | Port - $APP_PORT | Path - $BASE_DIR"
      - node --version
      - npm --version
      - npm ci --prefer-offline

  pre_build:
    commands:
      - echo "=== Pre-Build Phase ==="
      - echo "Fetching .env from SSM parameter /aitrillion/${ENV_NAME}/env-file"
      - aws ssm get-parameter --name "/aitrillion/${ENV_NAME}/env-file" --with-decryption --query "Parameter.Value" --output text > .env
      - echo ".env file created - line count:" && wc -l .env

  build:
    commands:
      - echo "=== Build Phase ==="
      - echo "Build started on $(date)"
      - npm run build
      - echo "Build completed on $(date)"

  post_build:
    commands:
      - echo "=== Post-Build Phase ==="
      - echo "export ENV_NAME=\"$ENV_NAME\"" > deployment_config.sh
      - echo "export APP_PORT=\"$APP_PORT\"" >> deployment_config.sh
      - echo "export BASE_DIR=\"$BASE_DIR\"" >> deployment_config.sh
      - echo "Deployment config created:"
      - cat deployment_config.sh

artifacts:
  files:
    - "**/*"
  base-directory: "."

cache:
  paths:
    - "node_modules/**/*"
    - ".next/cache/**/*"