import React, { useEffect, useState } from 'react';
import { Card, Tooltip, Spin } from 'antd';
import {
  ChartContainer,
  ColoredCheckbox,
  HeaderContainer,
  HeaderText,
  HeaderTextBold,
  Wrapper,
} from '../../style';
import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  XAxis,
  YAxis,
} from 'recharts';
import { InfoCircleOutlined } from '@ant-design/icons';
import logger from '@/utils/logger';
import { checkValidData } from '@/utils/common.util';
import AitCard from '@/components/atoms/ait-card/aitCard';

function currency(n) {
  return `$${(n ?? 0).toFixed(2)}`;
}

function CustomTooltip({ active, payload }) {
  if (!active || !payload || payload.length === 0) return null;

  const data = payload[0].payload;
  const redeemer = payload.find((p) => p.dataKey === 'redeemer')?.value ?? 0;
  const nonRedeemer =
    payload.find((p) => p.dataKey === 'nonRedeemer')?.value ?? 0;
  const nonMember = payload.find((p) => p.dataKey === 'nonMember')?.value ?? 0;

  return (
    <div
      style={{
        background: '#fff',
        border: '1px solid #eee',
        padding: 8,
        borderRadius: 6,
      }}
    >
      <div style={{ fontWeight: 600, marginBottom: 6 }}>
        {data?.label || data?.d}
      </div>

      <div>• Redeeming members: {currency(redeemer)}</div>
      <div>• Non-redeeming member: {currency(nonRedeemer)}</div>
      <div>• Non-member: {currency(nonMember)}</div>
    </div>
  );
}

export default function CustomerAverageOrderChart({
  apiData,
  setCheckboxChartState,
  checkboxChartState,
}) {
  const [data, setData] = useState([]);
  const [totals, setTotals] = useState({ redeemer: 0, other: 0 });
  const [loading, setLoading] = useState(true);

  // Fetch data from API
  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const transformedData = apiData?.lineChartData?.map((item) => ({
          d: item[0],
          redeemer: item[1],
          nonRedeemer: item[2],
          nonMember: item[3],
          label: item[4],
        }));
        setData(transformedData);
        const redeemerTotal = transformedData?.reduce(
          (sum, item) => sum + item.redeemer,
          0
        );
        const otherTotal = transformedData?.reduce(
          (sum, item) => sum + item.nonRedeemer + item.nonMember,
          0
        );
        setTotals({
          redeemer: redeemerTotal,
          other: otherTotal,
        });
      } catch (error) {
        logger(error);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [apiData]);
  if (loading) {
    return (
      <Spin
        size="large"
        style={{ display: 'flex', justifyContent: 'center', marginTop: '20px' }}
      />
    );
  }

  return (
    <AitCard
      hascustomheader={true}
      headerpadding={{ md: '24px 24px 10px 24px' }}
      customheaderleft={
        <>
          <HeaderContainer>
            <HeaderText as="h4">Customer average order value</HeaderText>
            <Tooltip
              placement="right"
              title="Expected value of revenue generated by a single customer throughout their entire relationship."
            >
              <InfoCircleOutlined />
            </Tooltip>
          </HeaderContainer>
          <HeaderTextBold style={{ visibility: 'hidden' }}>
            to manage space
          </HeaderTextBold>
        </>
      }
    >
      <ChartContainer $height={265}>
        <ResponsiveContainer>
          <LineChart data={data}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="date" />
            <YAxis allowDataOverflow />
            <Tooltip content={<CustomTooltip />} />
            {checkboxChartState?.customerRedeeminCheck && (
              <Line
                type="monotone"
                dataKey="redeemer"
                name="Redeeming members"
                stroke="#13c2c2"
                strokeWidth={2}
              />
            )}
            {checkboxChartState?.customerNonRedeeminCheck && (
              <Line
                type="monotone"
                dataKey="nonRedeemer"
                name="Non-redeeming members"
                stroke="#52c41a"
                strokeWidth={2}
              />
            )}
            {checkboxChartState?.customerNonMemberCheck && (
              <Line
                type="monotone"
                dataKey="nonMember"
                name="Non-members"
                stroke="#faad14"
                strokeWidth={2}
              />
            )}
          </LineChart>
        </ResponsiveContainer>
      </ChartContainer>

      <div style={{ marginTop: 80, borderTop: '1px solid #f1f5f9' }}>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            fontSize: 13,
          }}
        >
          <Wrapper>
            <HeaderContainer>
              <Tooltip
                placement="right"
                title="Redeeming members are customers who have actively engaged with the loyalty program by redeeming points to claim a reward."
              >
                <ColoredCheckbox
                  checkedColor="#6ca9ceff"
                  checked={checkboxChartState?.customerRedeeminCheck}
                  onChange={() =>
                    setCheckboxChartState({
                      ...checkboxChartState,
                      customerRedeeminCheck:
                        !checkboxChartState?.customerRedeeminCheck,
                    })
                  }
                >
                  Redeeming members
                </ColoredCheckbox>
                <InfoCircleOutlined />
              </Tooltip>
            </HeaderContainer>
          </Wrapper>
          <div style={{ fontWeight: 600 }}>
            {' '}
            {checkValidData(apiData?.lineRedeemingMemberWithFormat)}
          </div>
        </div>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            fontSize: 13,
            marginTop: 6,
          }}
        >
          <Wrapper>
            <HeaderContainer>
              <Tooltip
                placement="right"
                title="Non-redeemers are customers who have joined the loyalty program but have not yet made a direct engagement via redeeming points or rewards."
              >
                {/* <HeaderText style={{ marginRight: '4px', cursor: 'pointer' }}>
                  Non-redeeming members
                </HeaderText> */}
                <ColoredCheckbox
                  checkedColor="#5c4dff"
                  checked={checkboxChartState?.customerNonRedeeminCheck}
                  onChange={() =>
                    setCheckboxChartState({
                      ...checkboxChartState,
                      customerNonRedeeminCheck:
                        !checkboxChartState?.customerNonRedeeminCheck,
                    })
                  }
                >
                  Non-redeeming members
                </ColoredCheckbox>
                <InfoCircleOutlined />
              </Tooltip>
            </HeaderContainer>
          </Wrapper>
          <div style={{ fontWeight: 600 }}>
            {' '}
            {checkValidData(apiData?.lineNonRedeemingMemberWithFormat)}
          </div>
        </div>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            fontSize: 13,
            marginTop: 6,
          }}
        >
          <Wrapper>
            <HeaderContainer>
              <Tooltip
                placement="right"
                title="Non-members are customers who are not signed up for the loyalty program. These might be guest customers or those who have opted out of the loyalty program."
              >
                {/* <HeaderText style={{ marginRight: '4px', cursor: 'pointer' }}>
                  Non-members
                </HeaderText> */}
                <ColoredCheckbox
                  checkedColor="#2ed3dbff"
                  checked={checkboxChartState?.customerNonMemberCheck}
                  onChange={() =>
                    setCheckboxChartState({
                      ...checkboxChartState,
                      customerNonMemberCheck:
                        !checkboxChartState?.customerNonMemberCheck,
                    })
                  }
                >
                  Non-members
                </ColoredCheckbox>
                <InfoCircleOutlined />
              </Tooltip>
            </HeaderContainer>
          </Wrapper>
          <div style={{ fontWeight: 600 }}>
            {checkValidData(apiData?.lineNonMemberWithFormat)}
          </div>
        </div>
      </div>
    </AitCard>
  );
}
